--QUERY 1
SELECT EMPNAME FROM EMPLOYEE WHERE SALARY>13000 AND CITY='RAJKOT' OR CITY='BARODA'

--QUERY 2
SELECT EMPNAME FROM EMPLOYEE ORDER BY EMPNAME 

--QUERY 3
SELECT DISTINCT CITY FROM EMPLOYEE

--QUERY 4
UPDATE EMPLOYEE SET CITY=NULL WHERE EMPNAME='KEYUR' OR EMPNAME='BHOOMI'

--QUERY 5
SELECT EMPNAME FROM EMPLOYEE WHERE CITY IS NULL

--QUERY 6
DELETE EMPLOYEE WHERE SALARY>=14000

--QUERY 7
DELETE EMPLOYEE WHERE CITY='RAJKOT'

--QUERY 8
DELETE EMPLOYEE WHERE JOININGDATE='01-05-2007'

--QUERY 9
TRUNCATE TABLE EMPLOYEE

--QUERY 10
DROP TABLE EMPLOYEE

--QUERY 11
TRUNCATE TABLE DEPOSIT

--QUERY 12
DROP TABLE DEPOSIT

--QUERY 13
DROP TABLE BRANCH

--QUERY 14
DROP TABLE CUSTOMERS

--QUERY 15
DROP TABLE BORROW
