--1. Write a SQL query to determine the highest purchase amount made by each salesperson on '2012-08-17'.
--Return salesperson ID, purchase amount.
Select salesman_id,max(purch_amt)
From orders 
Where ord_date='2012-08-17'
Group by salesman_id


--2. Write a SQL query to find the highest order (purchase) amount by each customer on a particular order date.
--Filter the result by highest order (purchase) amount above 2000.00. Return customer id, order date and
--maximum purchase amount.
Select customer_id,ord_Date,max(purch_amt)
From orders
Group by customer_id,ord_Date
Having max(purch_amt)>2000


--3. Write a SQL query to find the maximum order (purchase) amount in the range 2000 - 6000 (Begin and end
--values are included.) by combination of each customer and order date. Return customer id, order date and
--maximum purchase amount.

Select customer_id,ord_date,max(purch_amt)
From orders
Group by customer_id,ord_date
Having max(purch_amt) between 2000 and 6000

--4. Write a SQL query to find the maximum order (purchase) amount based on the combination of each
--customer and order date. Filter the rows for maximum order (purchase) amount is either 2000, 3000, 5760,
--6000. Return customer id, order date and maximum purchase amount.

Select customer_id,ord_date,max(purch_amt)
From orders
Group by customer_id,ord_date
Having max(purch_amt) in (2000,3000,5760,6000)


--5. Write a SQL query to determine the maximum order amount for each customer. The customer ID should be
--in the range 3002 and 3007(Begin and end values are included.). Return customer id and maximum purchase
--amount.
Select customer_id,max(purch_amt)
From orders
where customer_id between 3002 and 3007
Group by customer_id


--6. Write a SQL query to find the maximum order (purchase) amount for each customer. The customer ID should
--be in the range 3002 and 3007(Begin and end values are included.). Filter the rows for maximum order
--(purchase) amount is higher than 1000. Return customer id and maximum purchase amount.
Select customer_id,max(purch_amt)
From orders
Where customer_id between 3002 and 3007
Group by customer_id
Having max(purch_amt)>1000


--7. Write a SQL query to determine the maximum order (purchase) amount generated by each salesperson.
--Filter the rows for the salesperson ID is in the range 5003 and 5008 (Begin and end values are included.).
--Return salesperson id and maximum purchase amount.

Select salesman_id,max(purch_amt)
From orders
Where salesman_id between 5003 and 5008
Group by salesman_id


--8. Write a SQL query to count all the orders generated on '2012-08-17'. Return number of orders.
Select count(ord_no) 
From orders
Where ord_date='2012-08-17'


--9. Write a SQL query to count the number of salespeople in a city. Return number of salespeople.
Select city,count(Salesman_id)
From salesmen
Group by city

--10. Write a SQL query to count the number of orders based on the combination of each order date and
--salesperson. Return order date, salesperson id.
Select ord_Date,salesman_id,count(ord_no)
From orders
Group by ord_date,salesman_id
