--QUERY1:
SELECT * FROM STUDENT2,RESULT;


--QUERY2:
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT2 S INNER JOIN RESULT R ON S.RNO=R.RNO 


--QUERY3:
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT2 S INNER JOIN RESULT R ON S.RNO=R.RNO WHERE S.BRANCH='CE' 


--QUERY4:
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT2 S INNER JOIN RESULT R ON S.RNO=R.RNO WHERE S.BRANCH!='EC' 


--QUERY5:
SELECT S.BRANCH,AVG(R.SPI) FROM STUDENT2 S INNER JOIN RESULT R ON S.RNO=R.RNO GROUP BY S.BRANCH 


--QUERY6:
SELECT S.BRANCH,AVG(R.SPI) FROM STUDENT2 S INNER JOIN RESULT R ON S.RNO=R.RNO GROUP BY S.BRANCH ORDER BY AVG(R.SPI)


--QUERY7:
SELECT S.BRANCH,AVG(R.SPI) FROM STUDENT2 S INNER JOIN RESULT R ON S.RNO=R.RNO WHERE S.BRANCH='CE' OR S.BRANCH='ME' GROUP BY S.BRANCH  


--QUERY8:
SELECT * FROM STUDENT2 S LEFT JOIN RESULT R ON S.RNO=R.RNO


--QUERY9:
SELECT * FROM STUDENT2 S RIGHT JOIN RESULT R ON S.RNO=R.RNO


--QUERY10:
SELECT * FROM STUDENT2 S FULL JOIN RESULT R ON S.RNO=R.RNO


--QUERY11:
SELECT E.NAME AS 'EMP_NAME',E1.NAME AS 'MAN_NAME' FROM EMPLOYEE1 E LEFT JOIN EMPLOYEE1 E1 ON E.MANAGERNO=E1.EMPLOYEENO 
